version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - noctx
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
  settings:
    gocyclo:
      min-complexity: 20
    goheader:
      values:
        regexp:
          copyright-year: 20[2-9]\d
      template-path: .golangci.goheader.template
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - examples/.*
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
